
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/act5?useSSL=true&useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/activity_test?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  # activiti default configuration
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
#    process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml
    history-level: full
debug: true
