package com.gome.statistic.infrastructure.mysql.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class HaiyanRcaReportToFilePath implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.914+08:00", comments="Source field: haiyan_rca_report_to_filepath.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.916+08:00", comments="Source field: haiyan_rca_report_to_filepath.racId")
    private String racid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.916+08:00", comments="Source field: haiyan_rca_report_to_filepath.file_name")
    private String fileName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.file_path")
    private String filePath;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.createTime")
    private Date createtime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.updateTime")
    private Date updatetime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.isFinished")
    private Integer isfinished;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.isUseable")
    private Integer isuseable;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.918+08:00", comments="Source field: haiyan_rca_report_to_filepath.ext")
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.916+08:00", comments="Source field: haiyan_rca_report_to_filepath.id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.916+08:00", comments="Source field: haiyan_rca_report_to_filepath.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.916+08:00", comments="Source field: haiyan_rca_report_to_filepath.racId")
    public String getRacid() {
        return racid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withRacid(String racid) {
        this.setRacid(racid);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.916+08:00", comments="Source field: haiyan_rca_report_to_filepath.racId")
    public void setRacid(String racid) {
        this.racid = racid == null ? null : racid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.916+08:00", comments="Source field: haiyan_rca_report_to_filepath.file_name")
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withFileName(String fileName) {
        this.setFileName(fileName);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.file_name")
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.file_path")
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withFilePath(String filePath) {
        this.setFilePath(filePath);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.file_path")
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.createTime")
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withCreatetime(Date createtime) {
        this.setCreatetime(createtime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.createTime")
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.updateTime")
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withUpdatetime(Date updatetime) {
        this.setUpdatetime(updatetime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.updateTime")
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.isFinished")
    public Integer getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withIsfinished(Integer isfinished) {
        this.setIsfinished(isfinished);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.isFinished")
    public void setIsfinished(Integer isfinished) {
        this.isfinished = isfinished;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.917+08:00", comments="Source field: haiyan_rca_report_to_filepath.isUseable")
    public Integer getIsuseable() {
        return isuseable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withIsuseable(Integer isuseable) {
        this.setIsuseable(isuseable);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.918+08:00", comments="Source field: haiyan_rca_report_to_filepath.isUseable")
    public void setIsuseable(Integer isuseable) {
        this.isuseable = isuseable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.918+08:00", comments="Source field: haiyan_rca_report_to_filepath.ext")
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    public HaiyanRcaReportToFilePath withExt(String ext) {
        this.setExt(ext);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-12T18:24:46.918+08:00", comments="Source field: haiyan_rca_report_to_filepath.ext")
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_report_to_filepath
     *
     * @mbg.generated Thu Dec 12 18:24:46 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", racid=").append(racid);
        sb.append(", fileName=").append(fileName);
        sb.append(", filePath=").append(filePath);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", isfinished=").append(isfinished);
        sb.append(", isuseable=").append(isuseable);
        sb.append(", ext=").append(ext);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}