package com.gome.statistic.infrastructure.mysql.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class HaiyanWorkOrderEntity implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.373+08:00", comments="Source field: haiyan_work_order.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.377+08:00", comments="Source field: haiyan_work_order.work_id")
    private String workId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.account")
    private String account;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.email")
    private String email;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.time")
    private Date time;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.center")
    private String center;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.ip_list")
    private String ipList;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.sys_args")
    private String sysArgs;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.diamond_content")
    private String diamondContent;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.domain")
    private String domain;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.domain_rule")
    private String domainRule;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.cdn_domain")
    private String cdnDomain;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.cdn_note")
    private String cdnNote;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.note")
    private String note;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.status")
    private String status;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.382+08:00", comments="Source field: haiyan_work_order.create_time")
    private Date createTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.382+08:00", comments="Source field: haiyan_work_order.resource")
    private String resource;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.user_cn")
    private String userCn;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.audit_note")
    private String auditNote;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.update_time")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.377+08:00", comments="Source field: haiyan_work_order.id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.377+08:00", comments="Source field: haiyan_work_order.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.377+08:00", comments="Source field: haiyan_work_order.work_id")
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withWorkId(String workId) {
        this.setWorkId(workId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.377+08:00", comments="Source field: haiyan_work_order.work_id")
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.account")
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withAccount(String account) {
        this.setAccount(account);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.account")
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.email")
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withEmail(String email) {
        this.setEmail(email);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.email")
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.time")
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withTime(Date time) {
        this.setTime(time);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.time")
    public void setTime(Date time) {
        this.time = time;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.378+08:00", comments="Source field: haiyan_work_order.center")
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withCenter(String center) {
        this.setCenter(center);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.center")
    public void setCenter(String center) {
        this.center = center == null ? null : center.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.ip_list")
    public String getIpList() {
        return ipList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withIpList(String ipList) {
        this.setIpList(ipList);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.ip_list")
    public void setIpList(String ipList) {
        this.ipList = ipList == null ? null : ipList.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.sys_args")
    public String getSysArgs() {
        return sysArgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withSysArgs(String sysArgs) {
        this.setSysArgs(sysArgs);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.379+08:00", comments="Source field: haiyan_work_order.sys_args")
    public void setSysArgs(String sysArgs) {
        this.sysArgs = sysArgs == null ? null : sysArgs.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.diamond_content")
    public String getDiamondContent() {
        return diamondContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withDiamondContent(String diamondContent) {
        this.setDiamondContent(diamondContent);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.diamond_content")
    public void setDiamondContent(String diamondContent) {
        this.diamondContent = diamondContent == null ? null : diamondContent.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.domain")
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withDomain(String domain) {
        this.setDomain(domain);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.domain")
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.domain_rule")
    public String getDomainRule() {
        return domainRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withDomainRule(String domainRule) {
        this.setDomainRule(domainRule);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.domain_rule")
    public void setDomainRule(String domainRule) {
        this.domainRule = domainRule == null ? null : domainRule.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.380+08:00", comments="Source field: haiyan_work_order.cdn_domain")
    public String getCdnDomain() {
        return cdnDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withCdnDomain(String cdnDomain) {
        this.setCdnDomain(cdnDomain);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.cdn_domain")
    public void setCdnDomain(String cdnDomain) {
        this.cdnDomain = cdnDomain == null ? null : cdnDomain.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.cdn_note")
    public String getCdnNote() {
        return cdnNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withCdnNote(String cdnNote) {
        this.setCdnNote(cdnNote);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.cdn_note")
    public void setCdnNote(String cdnNote) {
        this.cdnNote = cdnNote == null ? null : cdnNote.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.note")
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withNote(String note) {
        this.setNote(note);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.note")
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.381+08:00", comments="Source field: haiyan_work_order.status")
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withStatus(String status) {
        this.setStatus(status);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.382+08:00", comments="Source field: haiyan_work_order.status")
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.382+08:00", comments="Source field: haiyan_work_order.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.382+08:00", comments="Source field: haiyan_work_order.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.resource")
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withResource(String resource) {
        this.setResource(resource);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.resource")
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.user_cn")
    public String getUserCn() {
        return userCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withUserCn(String userCn) {
        this.setUserCn(userCn);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.user_cn")
    public void setUserCn(String userCn) {
        this.userCn = userCn == null ? null : userCn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.audit_note")
    public String getAuditNote() {
        return auditNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withAuditNote(String auditNote) {
        this.setAuditNote(auditNote);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.audit_note")
    public void setAuditNote(String auditNote) {
        this.auditNote = auditNote == null ? null : auditNote.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.update_time")
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    public HaiyanWorkOrderEntity withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T10:35:34.383+08:00", comments="Source field: haiyan_work_order.update_time")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_work_order
     *
     * @mbg.generated Mon Nov 11 10:35:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", workId=").append(workId);
        sb.append(", account=").append(account);
        sb.append(", email=").append(email);
        sb.append(", time=").append(time);
        sb.append(", center=").append(center);
        sb.append(", ipList=").append(ipList);
        sb.append(", sysArgs=").append(sysArgs);
        sb.append(", diamondContent=").append(diamondContent);
        sb.append(", domain=").append(domain);
        sb.append(", domainRule=").append(domainRule);
        sb.append(", cdnDomain=").append(cdnDomain);
        sb.append(", cdnNote=").append(cdnNote);
        sb.append(", note=").append(note);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", resource=").append(resource);
        sb.append(", userCn=").append(userCn);
        sb.append(", auditNote=").append(auditNote);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}