package com.gome.statistic.infrastructure.mysql.entity;

import java.io.Serializable;
import javax.annotation.Generated;

public class HaiyanRcaChangerFlow implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33+08:00", comments="Source field: haiyan_rca_changer_flow.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.rca_id")
    private String rcaId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.change_id")
    private String changeId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_name")
    private String personName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_account")
    private String personAccount;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_plan_status")
    private Integer personPlanStatus;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.change_flow_status")
    private Integer changeFlowStatus;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.is_finished")
    private Integer isFinished;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.feedback_result")
    private String feedbackResult;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.004+08:00", comments="Source field: haiyan_rca_changer_flow.report_detail")
    private String reportDetail;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.004+08:00", comments="Source field: haiyan_rca_changer_flow.person_feedback")
    private String personFeedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.rca_id")
    public String getRcaId() {
        return rcaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withRcaId(String rcaId) {
        this.setRcaId(rcaId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.rca_id")
    public void setRcaId(String rcaId) {
        this.rcaId = rcaId == null ? null : rcaId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.change_id")
    public String getChangeId() {
        return changeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withChangeId(String changeId) {
        this.setChangeId(changeId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.002+08:00", comments="Source field: haiyan_rca_changer_flow.change_id")
    public void setChangeId(String changeId) {
        this.changeId = changeId == null ? null : changeId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_name")
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withPersonName(String personName) {
        this.setPersonName(personName);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_name")
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_account")
    public String getPersonAccount() {
        return personAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withPersonAccount(String personAccount) {
        this.setPersonAccount(personAccount);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_account")
    public void setPersonAccount(String personAccount) {
        this.personAccount = personAccount == null ? null : personAccount.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_plan_status")
    public Integer getPersonPlanStatus() {
        return personPlanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withPersonPlanStatus(Integer personPlanStatus) {
        this.setPersonPlanStatus(personPlanStatus);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.person_plan_status")
    public void setPersonPlanStatus(Integer personPlanStatus) {
        this.personPlanStatus = personPlanStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.change_flow_status")
    public Integer getChangeFlowStatus() {
        return changeFlowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withChangeFlowStatus(Integer changeFlowStatus) {
        this.setChangeFlowStatus(changeFlowStatus);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.change_flow_status")
    public void setChangeFlowStatus(Integer changeFlowStatus) {
        this.changeFlowStatus = changeFlowStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.is_finished")
    public Integer getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withIsFinished(Integer isFinished) {
        this.setIsFinished(isFinished);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.is_finished")
    public void setIsFinished(Integer isFinished) {
        this.isFinished = isFinished;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.003+08:00", comments="Source field: haiyan_rca_changer_flow.feedback_result")
    public String getFeedbackResult() {
        return feedbackResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withFeedbackResult(String feedbackResult) {
        this.setFeedbackResult(feedbackResult);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.004+08:00", comments="Source field: haiyan_rca_changer_flow.feedback_result")
    public void setFeedbackResult(String feedbackResult) {
        this.feedbackResult = feedbackResult == null ? null : feedbackResult.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.004+08:00", comments="Source field: haiyan_rca_changer_flow.report_detail")
    public String getReportDetail() {
        return reportDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withReportDetail(String reportDetail) {
        this.setReportDetail(reportDetail);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.004+08:00", comments="Source field: haiyan_rca_changer_flow.report_detail")
    public void setReportDetail(String reportDetail) {
        this.reportDetail = reportDetail == null ? null : reportDetail.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.004+08:00", comments="Source field: haiyan_rca_changer_flow.person_feedback")
    public String getPersonFeedback() {
        return personFeedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    public HaiyanRcaChangerFlow withPersonFeedback(String personFeedback) {
        this.setPersonFeedback(personFeedback);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T14:43:33.004+08:00", comments="Source field: haiyan_rca_changer_flow.person_feedback")
    public void setPersonFeedback(String personFeedback) {
        this.personFeedback = personFeedback == null ? null : personFeedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_changer_flow
     *
     * @mbg.generated Mon Dec 02 14:43:33 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rcaId=").append(rcaId);
        sb.append(", changeId=").append(changeId);
        sb.append(", personName=").append(personName);
        sb.append(", personAccount=").append(personAccount);
        sb.append(", personPlanStatus=").append(personPlanStatus);
        sb.append(", changeFlowStatus=").append(changeFlowStatus);
        sb.append(", isFinished=").append(isFinished);
        sb.append(", feedbackResult=").append(feedbackResult);
        sb.append(", reportDetail=").append(reportDetail);
        sb.append(", personFeedback=").append(personFeedback);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}