package com.gome.statistic.infrastructure.mysql.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class HaiyanRcaSolution implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.271+08:00", comments="Source field: haiyan_rca_solution.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.rca_id")
    private String rcaId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.rcaid_to_changeid")
    private Long rcaidToChangeid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.change_id")
    private String changeId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_account")
    private String personAccount;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_name")
    private String personName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_email")
    private String personEmail;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.plan_finish_time")
    private Date planFinishTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.finished_time")
    private Date finishedTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.is_finished")
    private Integer isFinished;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.change_status")
    private Integer changeStatus;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.is_useable")
    private Integer isUseable;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.change_context")
    private String changeContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.276+08:00", comments="Source field: haiyan_rca_solution.id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.rca_id")
    public String getRcaId() {
        return rcaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withRcaId(String rcaId) {
        this.setRcaId(rcaId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.rca_id")
    public void setRcaId(String rcaId) {
        this.rcaId = rcaId == null ? null : rcaId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.rcaid_to_changeid")
    public Long getRcaidToChangeid() {
        return rcaidToChangeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withRcaidToChangeid(Long rcaidToChangeid) {
        this.setRcaidToChangeid(rcaidToChangeid);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.rcaid_to_changeid")
    public void setRcaidToChangeid(Long rcaidToChangeid) {
        this.rcaidToChangeid = rcaidToChangeid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.change_id")
    public String getChangeId() {
        return changeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withChangeId(String changeId) {
        this.setChangeId(changeId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.277+08:00", comments="Source field: haiyan_rca_solution.change_id")
    public void setChangeId(String changeId) {
        this.changeId = changeId == null ? null : changeId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_account")
    public String getPersonAccount() {
        return personAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withPersonAccount(String personAccount) {
        this.setPersonAccount(personAccount);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_account")
    public void setPersonAccount(String personAccount) {
        this.personAccount = personAccount == null ? null : personAccount.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_name")
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withPersonName(String personName) {
        this.setPersonName(personName);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_name")
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_email")
    public String getPersonEmail() {
        return personEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withPersonEmail(String personEmail) {
        this.setPersonEmail(personEmail);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.person_email")
    public void setPersonEmail(String personEmail) {
        this.personEmail = personEmail == null ? null : personEmail.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.plan_finish_time")
    public Date getPlanFinishTime() {
        return planFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withPlanFinishTime(Date planFinishTime) {
        this.setPlanFinishTime(planFinishTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.plan_finish_time")
    public void setPlanFinishTime(Date planFinishTime) {
        this.planFinishTime = planFinishTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.finished_time")
    public Date getFinishedTime() {
        return finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withFinishedTime(Date finishedTime) {
        this.setFinishedTime(finishedTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.278+08:00", comments="Source field: haiyan_rca_solution.finished_time")
    public void setFinishedTime(Date finishedTime) {
        this.finishedTime = finishedTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.is_finished")
    public Integer getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withIsFinished(Integer isFinished) {
        this.setIsFinished(isFinished);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.is_finished")
    public void setIsFinished(Integer isFinished) {
        this.isFinished = isFinished;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.change_status")
    public Integer getChangeStatus() {
        return changeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withChangeStatus(Integer changeStatus) {
        this.setChangeStatus(changeStatus);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.change_status")
    public void setChangeStatus(Integer changeStatus) {
        this.changeStatus = changeStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.is_useable")
    public Integer getIsUseable() {
        return isUseable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withIsUseable(Integer isUseable) {
        this.setIsUseable(isUseable);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.is_useable")
    public void setIsUseable(Integer isUseable) {
        this.isUseable = isUseable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.change_context")
    public String getChangeContext() {
        return changeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    public HaiyanRcaSolution withChangeContext(String changeContext) {
        this.setChangeContext(changeContext);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-12-02T10:37:52.279+08:00", comments="Source field: haiyan_rca_solution.change_context")
    public void setChangeContext(String changeContext) {
        this.changeContext = changeContext == null ? null : changeContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_rca_solution
     *
     * @mbg.generated Mon Dec 02 10:37:52 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rcaId=").append(rcaId);
        sb.append(", rcaidToChangeid=").append(rcaidToChangeid);
        sb.append(", changeId=").append(changeId);
        sb.append(", personAccount=").append(personAccount);
        sb.append(", personName=").append(personName);
        sb.append(", personEmail=").append(personEmail);
        sb.append(", planFinishTime=").append(planFinishTime);
        sb.append(", finishedTime=").append(finishedTime);
        sb.append(", isFinished=").append(isFinished);
        sb.append(", changeStatus=").append(changeStatus);
        sb.append(", isUseable=").append(isUseable);
        sb.append(", changeContext=").append(changeContext);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}