package com.gome.statistic.infrastructure.mysql.entity;

import com.gome.statistic.infrastructure.mysql.mapper.HaiyanAppEntityDynamicSqlSupport;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class HaiyanAppEntity implements Serializable {

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-10-15T15:02:01.623+08:00", comments="Source Table: haiyan_app")
    public static final HaiyanAppEntity haiyanAppEntity = new HaiyanAppEntity();

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.278+08:00", comments="Source field: haiyan_app.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.code")
    private String code;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.port")
    private Integer port;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.mem")
    private String mem;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.middleware")
    private String middleware;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.jdk")
    private String jdk;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.sre")
    private Byte sre;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.create_time")
    private Date createTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.update_time")
    private Date updateTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.work_id")
    private String workId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.note")
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.name")
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withName(String name) {
        this.setName(name);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.name")
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.code")
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withCode(String code) {
        this.setCode(code);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.280+08:00", comments="Source field: haiyan_app.code")
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.port")
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withPort(Integer port) {
        this.setPort(port);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.port")
    public void setPort(Integer port) {
        this.port = port;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.mem")
    public String getMem() {
        return mem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withMem(String mem) {
        this.setMem(mem);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.mem")
    public void setMem(String mem) {
        this.mem = mem == null ? null : mem.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.middleware")
    public String getMiddleware() {
        return middleware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withMiddleware(String middleware) {
        this.setMiddleware(middleware);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.middleware")
    public void setMiddleware(String middleware) {
        this.middleware = middleware == null ? null : middleware.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.jdk")
    public String getJdk() {
        return jdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withJdk(String jdk) {
        this.setJdk(jdk);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.281+08:00", comments="Source field: haiyan_app.jdk")
    public void setJdk(String jdk) {
        this.jdk = jdk == null ? null : jdk.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.sre")
    public Byte getSre() {
        return sre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withSre(Byte sre) {
        this.setSre(sre);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.sre")
    public void setSre(Byte sre) {
        this.sre = sre;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.update_time")
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.update_time")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.work_id")
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withWorkId(String workId) {
        this.setWorkId(workId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.work_id")
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.282+08:00", comments="Source field: haiyan_app.note")
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    public HaiyanAppEntity withNote(String note) {
        this.setNote(note);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-11-11T11:00:07.283+08:00", comments="Source field: haiyan_app.note")
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_app
     *
     * @mbg.generated Mon Nov 11 11:00:07 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", port=").append(port);
        sb.append(", mem=").append(mem);
        sb.append(", middleware=").append(middleware);
        sb.append(", jdk=").append(jdk);
        sb.append(", sre=").append(sre);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", workId=").append(workId);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}