server:
  port: 8082
spring:
  profiles:
    active: dev
---
server:
  port: 8083
spring:
  profiles: dev

---

server:
  port: 8084
spring:
  profiles: prod
---





person:
  lastName: nihui
  age: 23
  boss: false
  date: 1995/01/08
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: xiaogou
    age: 2





